# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombres')),
                ('surnames', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('country', models.CharField(max_length=20, verbose_name='País')),
                ('cellphone', models.IntegerField(verbose_name='Celular')),
                ('phono', models.IntegerField(verbose_name='Telefono')),
                ('address', models.CharField(max_length=50, verbose_name='Dirección')),
            ],
        ),
    ]
