# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_person_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationcode',
            name='description',
            field=models.CharField(default='Create', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='country',
            field=models.CharField(choices=[('Bolivia', 'Bolivia'), ('Argentina', 'Argentina')], max_length=20, verbose_name='País'),
        ),
    ]
