# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 16:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha de Publicaciòn')),
            ],
        ),
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenido de la Publicaciòn')),
                ('type', models.CharField(choices=[('image', 'Imagen'), ('video', 'Video'), ('page', 'Pagina')], max_length=10, verbose_name='Tipo de Publicaciòn')),
                ('link', models.URLField(default='', verbose_name='Direccón del Enlace')),
                ('state', models.BooleanField(default=False)),
                ('start', models.BooleanField(default=False)),
                ('ends', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dates',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publishers.Publishers'),
        ),
    ]
