# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dates',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='publishers',
            name='link',
            field=models.URLField(blank=True, verbose_name='Direccón del Enlace'),
        ),
        migrations.AlterField(
            model_name='publishers',
            name='type',
            field=models.CharField(choices=[('text', 'Texto'), ('image', 'Imagen'), ('video', 'Video'), ('page', 'Pagina')], max_length=10, verbose_name='Tipo de Publicaciòn'),
        ),
    ]
